spring.application.name=inventory-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5436/inventory_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.jewelrystore.inventory.event.VariantCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/