spring.application.name=cart-service
server.port=8085

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# External Services
inventory.service.url=http://localhost:8084
product.service.url=http://localhost:8083

# Cart TTL (in seconds)
cart.ttl.guest=604800
cart.ttl.user=2592000

jwt.secret=${JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/